from django.urls import path
from .views import (
    warranty_new,
    warranty_my_claims,
    warranty_claim_detail,
    warranty_track,
    warranty_staff_list,
    warranty_staff_detail,
    warranty_staff_action,
    agency_application_action,
    agency_application_detail,
    agency_applications_list,
    agency_application_track,
    agency_register_apply,
    agency_register_phone,
    agency_register_success,
    agency_register_verify,
    receipt_reader_test,
    sms_mfa_setup,
    sms_otp_verify,
    sms_test_send,
    bank_names_autocomplete,
    counterparty_edit,
    counterparties_manage,
    create_payment,
    customer_daily_payments,
    customer_detail,
    customers_list,
    daily_payment_plan_detail,
    daily_payment_plans,
    edit_payment,
    export_data,
    export_records,
    invoice_detail,
    invoice_delete,
    invoice_file,
    invoice_parse_preview,
    invoice_parse_status,
    invoices_dashboard,
    legacy_payment_receipt_file,
    login_ad_image,
    notifications_feed,
    notifications_mark_read,
    order_detail,
    orders_dashboard,
    profile_edit,
    profile_change_request_review,
    profile_password_cancel,
    profile_password_change,
    payment_timeline,
    payment_history,
    proforma_detail,
    proforma_delete,
    proforma_file,
    proformas_dashboard,
    price_list_file,
    price_list_delete,
    price_lists_dashboard,
    reconciliation_center,
    reconciliation_poll,
    reconciliation_messages_feed,
    reconciliation_attachment_download,
    payment_start_thread,
    add_payment_note,
    delegate_final_approval,
    final_approval_delegation_page,
    finance_bulk_final_approve,
    finance_final_approve,
    finance_register_payment,
    finance_unified_action,
    pending_final_approval_queue,
    counterparty_approve_payment,
    counterparty_dashboard,
    counterparty_manage_edit,
    counterparty_manage_list,
    counterparty_reject_payment_cp,
    counterparty_return_payment,
    counterparty_return_payment_cp,
    import_product_catalog,
    import_customer_accounting_codes,
    product_catalog_search,
    sales_expert_dashboard,
    receipt_file,
    rotate_receipt,
    reset_user_password,
    sales_assignments_dashboard,
    staff_update_status,
    staff_edit_payment_details,
    success,
    system_logo_settings,
    user_business_card,
    user_edit,
    users_manage,
    access_management,
    access_management_edit,
)

urlpatterns = [
    # ─── پلتفرم درخواست نمایندگی (عمومی) ───────────────────────────────────────
    path('agency/', agency_register_phone, name='agency_register'),
    path('agency/verify/', agency_register_verify, name='agency_verify'),
    path('agency/apply/', agency_register_apply, name='agency_apply'),
    path('agency/track/', agency_application_track, name='agency_track'),
    path('agency/success/<str:tracking_code>/', agency_register_success, name='agency_success'),
    # ─── مدیریت نمایندگی (کارشناس/مدیر فروش) ──────────────────────────────────
    path('sales/agency/', agency_applications_list, name='agency_applications'),
    path('sales/agency/<int:app_id>/', agency_application_detail, name='agency_application_detail'),
    path('sales/agency/<int:app_id>/action/', agency_application_action, name='agency_application_action'),
    path('submit/', create_payment, name='submit'),
    path('submit/new/', create_payment, name='payment_create'),
    path('my-daily-payments/', customer_daily_payments, name='customer_daily_payments'),
    path('success/', success, name='success'),
    path('api/bank-names/', bank_names_autocomplete, name='bank_names_autocomplete'),
    path('api/notifications/', notifications_feed, name='notifications_feed'),
    path('api/notifications/read/', notifications_mark_read, name='notifications_mark_read'),
    path('api/reconciliation-messages/', reconciliation_messages_feed, name='reconciliation_messages_feed'),
    path('customer/<int:user_id>/', customer_detail, name='customer_detail'),
    path('customers/', customers_list, name='customers_list'),
    path('customers/import-accounting-codes/', import_customer_accounting_codes, name='import_customer_accounting_codes'),
    path('daily-payments/', daily_payment_plans, name='daily_payment_plans'),
    path('daily-payments/<int:plan_id>/', daily_payment_plan_detail, name='daily_payment_plan_detail'),
    path('users/reset-password/<int:user_id>/', reset_user_password, name='reset_user_password'),
    path('payments/<int:payment_id>/status/', staff_update_status, name='staff_update_status'),
    path('payments/<int:payment_id>/finance-register/', finance_register_payment, name='finance_register_payment'),
    path('payments/<int:payment_id>/finance-action/', finance_unified_action, name='finance_unified_action'),
    path('payments/<int:payment_id>/delegate-approve/', delegate_final_approval, name='delegate_final_approval'),
    path('finance/pending-final-approval/', pending_final_approval_queue, name='pending_final_approval'),
    path('finance/delegation/', final_approval_delegation_page, name='final_approval_delegation'),
    path('finance/bulk-approve/', finance_bulk_final_approve, name='finance_bulk_final_approve'),
    path('finance/reconciliation/', reconciliation_center, name='reconciliation_center'),
    path('finance/reconciliation/poll/', reconciliation_poll, name='reconciliation_poll'),
    path('finance/reconciliation/attachments/<int:message_id>/', reconciliation_attachment_download, name='reconciliation_attachment_download'),
    path('finance/reconciliation/start-thread/', payment_start_thread, name='payment_start_thread'),
    path('payments/<int:payment_id>/final-approve/', finance_final_approve, name='finance_final_approve'),
    path('payments/<int:payment_id>/details-edit/', staff_edit_payment_details, name='staff_edit_payment_details'),
    path('payments/<int:payment_id>/edit/', edit_payment, name='edit_payment'),
    path('payments/<int:payment_id>/timeline/', payment_timeline, name='payment_timeline'),
    path('payments/<int:payment_id>/note/', add_payment_note, name='add_payment_note'),
    path('payments/history/', payment_history, name='payment_history'),
    path('payments/<int:payment_id>/receipt-file/', legacy_payment_receipt_file, name='legacy_payment_receipt_file'),
    path('receipts/<int:receipt_id>/file/', receipt_file, name='receipt_file'),
    path('receipts/<int:receipt_id>/rotate/', rotate_receipt, name='rotate_receipt'),
    path('invoices/', invoices_dashboard, name='invoices_dashboard'),
    path('invoices/parse-preview/', invoice_parse_preview, name='invoice_parse_preview'),
    path('invoices/parse-preview/<int:job_id>/', invoice_parse_status, name='invoice_parse_status'),
    path('invoices/<int:invoice_id>/', invoice_detail, name='invoice_detail'),
    path('invoices/<int:invoice_id>/file/', invoice_file, name='invoice_file'),
    path('invoices/<int:invoice_id>/delete/', invoice_delete, name='invoice_delete'),
    path('price-lists/', price_lists_dashboard, name='price_lists'),
    path('price-lists/<int:price_list_id>/file/', price_list_file, name='price_list_file'),
    path('price-lists/<int:price_list_id>/delete/', price_list_delete, name='price_list_delete'),
    path('orders/', orders_dashboard, name='orders'),
    path('products/search/', product_catalog_search, name='product_catalog_search'),
    path('products/import/', import_product_catalog, name='import_product_catalog'),
    path('sales-assignments/', sales_assignments_dashboard, name='sales_assignments'),
    path('sales/dashboard/', sales_expert_dashboard, name='sales_expert_dashboard'),
    path('counterparty/', counterparty_dashboard, name='counterparty_dashboard'),
    path('counterparty/payments/<int:payment_id>/approve/', counterparty_approve_payment, name='counterparty_approve_payment'),
    path('counterparty/payments/<int:payment_id>/return-cp/', counterparty_return_payment_cp, name='counterparty_return_payment_cp'),
    path('counterparty/payments/<int:payment_id>/reject-cp/', counterparty_reject_payment_cp, name='counterparty_reject_payment_cp'),
    path('counterparty/payments/<int:payment_id>/return/', counterparty_return_payment, name='counterparty_return_payment'),
    path('orders/<int:order_id>/', order_detail, name='order_detail'),
    path('proformas/', proformas_dashboard, name='proformas'),
    path('proformas/<int:proforma_id>/', proforma_detail, name='proforma_detail'),
    path('proformas/<int:proforma_id>/file/', proforma_file, name='proforma_file'),
    path('proformas/<int:proforma_id>/delete/', proforma_delete, name='proforma_delete'),
    path('login-ads/<int:ad_id>/image/', login_ad_image, name='login_ad_image'),
    path('users/', users_manage, name='users_manage'),
    path('users/<int:user_id>/card/', user_business_card, name='user_business_card'),
    path('users/<int:user_id>/edit/', user_edit, name='user_edit'),
    path('access-management/', access_management, name='access_management'),
    path('access-management/<int:user_id>/edit/', access_management_edit, name='access_management_edit'),
    path('counterparties/', counterparties_manage, name='counterparties_manage'),
    path('counterparties/manage/', counterparty_manage_list, name='counterparty_manage_list'),
    path('counterparties/manage/new/', counterparty_manage_edit, name='counterparty_manage_create'),
    path('counterparties/manage/<int:cp_id>/', counterparty_manage_edit, name='counterparty_manage_edit'),
    path('counterparties/<int:counterparty_id>/edit/', counterparty_edit, name='counterparty_edit'),
    path('export-records/', export_records, name='export_records'),
    path('export/<str:dataset>/', export_data, name='export_data'),
    path('admin-tools/receipt-reader/', receipt_reader_test, name='receipt_reader_test'),
    path('admin-tools/system-logo/', system_logo_settings, name='system_logo_settings'),
    path('sms-verify/', sms_otp_verify, name='sms_otp_verify'),
    path('sms-mfa/setup/', sms_mfa_setup, name='sms_mfa_setup'),
    path('sms-mfa/test/', sms_test_send, name='sms_test_send'),
    path('profile/', profile_edit, name='profile_edit'),
    path('profile-change-requests/<int:request_id>/review/', profile_change_request_review, name='profile_change_request_review'),
    path('profile/password/', profile_password_change, name='profile_password_change'),
    path('profile/password/cancel/', profile_password_cancel, name='profile_password_cancel'),

    # ─── گارانتی و خدمات پس از فروش ─────────────────────────────────────────────
    path('warranty/',                          warranty_new,          name='warranty_new'),
    path('warranty/my/',                       warranty_my_claims,    name='warranty_my_claims'),
    path('warranty/track/',                    warranty_track,        name='warranty_track'),
    path('warranty/<int:claim_id>/',           warranty_claim_detail, name='warranty_claim_detail'),
    path('warranty/staff/',                    warranty_staff_list,   name='warranty_staff_list'),
    path('warranty/staff/<int:claim_id>/',     warranty_staff_detail, name='warranty_staff_detail'),
    path('warranty/staff/<int:claim_id>/action/', warranty_staff_action, name='warranty_staff_action'),
]
