from django.urls import path
from .views import (
    bank_names_autocomplete,
    counterparty_edit,
    counterparties_manage,
    create_payment,
    customer_detail,
    customers_list,
    daily_payment_plan_detail,
    daily_payment_plans,
    edit_payment,
    export_data,
    export_records,
    invoice_detail,
    invoice_file,
    invoices_dashboard,
    legacy_payment_receipt_file,
    login_ad_image,
    notifications_feed,
    notifications_mark_read,
    profile_edit,
    profile_password_cancel,
    profile_password_change,
    payment_timeline,
    payment_history,
    price_list_file,
    price_lists_dashboard,
    receipt_file,
    reset_user_password,
    staff_update_status,
    staff_edit_payment_details,
    success,
    user_edit,
    users_manage,
)

urlpatterns = [
    path('submit/', create_payment, name='submit'),
    path('success/', success, name='success'),
    path('api/bank-names/', bank_names_autocomplete, name='bank_names_autocomplete'),
    path('api/notifications/', notifications_feed, name='notifications_feed'),
    path('api/notifications/read/', notifications_mark_read, name='notifications_mark_read'),
    path('customer/<int:user_id>/', customer_detail, name='customer_detail'),
    path('customers/', customers_list, name='customers_list'),
    path('daily-payments/', daily_payment_plans, name='daily_payment_plans'),
    path('daily-payments/<int:plan_id>/', daily_payment_plan_detail, name='daily_payment_plan_detail'),
    path('users/reset-password/<int:user_id>/', reset_user_password, name='reset_user_password'),
    path('payments/<int:payment_id>/status/', staff_update_status, name='staff_update_status'),
    path('payments/<int:payment_id>/details-edit/', staff_edit_payment_details, name='staff_edit_payment_details'),
    path('payments/<int:payment_id>/edit/', edit_payment, name='edit_payment'),
    path('payments/<int:payment_id>/timeline/', payment_timeline, name='payment_timeline'),
    path('payments/history/', payment_history, name='payment_history'),
    path('payments/<int:payment_id>/receipt-file/', legacy_payment_receipt_file, name='legacy_payment_receipt_file'),
    path('receipts/<int:receipt_id>/file/', receipt_file, name='receipt_file'),
    path('invoices/', invoices_dashboard, name='invoices_dashboard'),
    path('invoices/<int:invoice_id>/', invoice_detail, name='invoice_detail'),
    path('invoices/<int:invoice_id>/file/', invoice_file, name='invoice_file'),
    path('price-lists/', price_lists_dashboard, name='price_lists'),
    path('price-lists/<int:price_list_id>/file/', price_list_file, name='price_list_file'),
    path('login-ads/<int:ad_id>/image/', login_ad_image, name='login_ad_image'),
    path('users/', users_manage, name='users_manage'),
    path('users/<int:user_id>/edit/', user_edit, name='user_edit'),
    path('counterparties/', counterparties_manage, name='counterparties_manage'),
    path('counterparties/<int:counterparty_id>/edit/', counterparty_edit, name='counterparty_edit'),
    path('export-records/', export_records, name='export_records'),
    path('export/<str:dataset>/', export_data, name='export_data'),
    path('profile/', profile_edit, name='profile_edit'),
    path('profile/password/', profile_password_change, name='profile_password_change'),
    path('profile/password/cancel/', profile_password_cancel, name='profile_password_cancel'),
]
