# Generated by Django 6.0.2 on 2026-02-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پیگیری'),
        ),
    ]
