# Generated by Django 6.0.2 on 2026-02-06 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentrecord_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('organization', models.CharField(blank=True, max_length=100, verbose_name='نام مجموعه')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='شهر')),
                ('role', models.CharField(choices=[('customer', 'مشتری'), ('staff', 'کارمند')], default='customer', max_length=10, verbose_name='نوع کاربر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
