# Generated by Django 6.0.2 on 2026-02-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Ø¯Ø± Ø­Ø§Ù„ Ø¨Ø±Ø±Ø³ÛŒ'), ('reviewed', 'Ø¨Ø±Ø±Ø³ÛŒ Ø´Ø¯Ù‡'), ('approved', 'ØªØ£ÛŒÛŒØ¯ Ø´Ø¯Ù‡'), ('rejected', 'Ø±Ø¯ Ø´Ø¯Ù‡'), ('archived', 'Ø¨Ø§ÛŒÚ¯Ø§Ù†ÛŒ Ø´Ø¯Ù‡')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Ù…Ø´ØªØ±ÛŒ'), ('finance', 'ÙˆØ§Ø­Ø¯ Ù…Ø§Ù„ÛŒ'), ('commercial', 'ÙˆØ§Ø­Ø¯ Ø¨Ø§Ø²Ø±Ú¯Ø§Ù†ÛŒ'), ('staff', 'Ú©Ø§Ø±Ù…Ù†Ø¯')], default='customer', max_length=10, verbose_name='Ù†ÙˆØ¹ Ú©Ø§Ø±Ø¨Ø±'),
        ),
    ]
