# Generated by Django 6.0.2 on 2026-02-14 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymentrecord_status_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('reviewed', 'بررسی شده'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('archived', 'بایگانی شده')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'مشتری'), ('finance', 'واحد مالی'), ('commercial', 'واحد بازرگانی'), ('staff', 'کارمند')], default='customer', max_length=10, verbose_name='نوع کاربر'),
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipts/')),
                ('file_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='payments.paymentrecord')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('payment', 'file_hash'), name='uniq_payment_receipt_hash')],
            },
        ),
    ]
