# Generated by Django 6.0.2 on 2026-02-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_counterparty_alter_paymentrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('commercial_review', 'بررسی بازرگانی'), ('finance_review', 'تایید مالی'), ('approved', 'تایید شده'), ('final_approved', 'تایید نهایی'), ('rejected', 'رد شده'), ('incomplete', 'ناقص'), ('returned_commercial', 'عودت به بازرگانی')], default='pending', max_length=20),
        ),
    ]
