# Generated by Django 6.0.2 on 2026-02-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_paymentrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='locked_by_finance',
            field=models.BooleanField(default=False),
        ),
    ]
