# Generated by Django 6.0.2 on 2026-02-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_paymentrecord_locked_by_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='payer_account_number',
            field=models.CharField(blank=True, default='Z', max_length=64),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='payer_first_name',
            field=models.CharField(blank=True, default='Z', max_length=64),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='payer_last_name',
            field=models.CharField(blank=True, default='Z', max_length=64),
        ),
    ]
