# Generated by Django 6.0.2 on 2026-02-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_paymentrecord_payer_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='payer_bank_branch',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='payer_bank_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payer_account_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payer_first_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payer_last_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
