# Generated by Django 6.0.2 on 2026-02-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_paymentrecord_payer_bank_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(choices=[(1, 'کادر 1'), (2, 'کادر 2'), (3, 'کادر 3'), (4, 'کادر 4')], unique=True, verbose_name='جایگاه')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان آگهی')),
                ('description', models.TextField(blank=True, verbose_name='متن آگهی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='login_ads/', verbose_name='تصویر بنر')),
                ('link_url', models.URLField(blank=True, verbose_name='لینک مقصد')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ خاتمه')),
                ('is_visible', models.BooleanField(default=True, verbose_name='نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'آگهی صفحه ورود',
                'verbose_name_plural': 'آگهی های صفحه ورود',
                'ordering': ['slot'],
            },
        ),
    ]
