# Generated by Django 6.0.2 on 2026-02-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_loginadvertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceipt',
            name='image',
            field=models.FileField(upload_to='receipts/'),
        ),
    ]
