# Generated by Django 6.0.2 on 2026-02-19 20:09

from django.db import migrations, models


def forward_fill_full_name(apps, schema_editor):
    PaymentRecord = apps.get_model('payments', 'PaymentRecord')
    for record in PaymentRecord.objects.all().iterator():
        first = (getattr(record, 'payer_first_name', '') or '').strip()
        last = (getattr(record, 'payer_last_name', '') or '').strip()
        if first == 'Z':
            first = ''
        if last == 'Z':
            last = ''
        full_name = f"{first} {last}".strip()
        if not full_name:
            full_name = 'Z'
        record.payer_full_name = full_name
        record.save(update_fields=['payer_full_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_paymentreceipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='payer_full_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.RunPython(forward_fill_full_name, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='payer_bank_branch',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='payer_first_name',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='payer_last_name',
        ),
    ]
