# Generated by Django 6.0.2 on 2026-02-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_remove_paymentrecord_payer_bank_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='beneficiary_account_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='beneficiary_account_owner',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
