# Generated by Django 6.0.2 on 2026-02-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_paymentrecord_beneficiary_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='beneficiary_bank_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
