# Generated by Django 6.0.2 on 2026-02-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_paymentrecord_beneficiary_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='force_password_change',
            field=models.BooleanField(default=True, verbose_name='الزام تعویض رمز'),
        ),
    ]
