# Generated by Django 6.0.2 on 2026-04-28 21:13

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_userprofile_force_password_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ')),
                ('invoice_date', django_jalali.db.models.jDateField(verbose_name='تاریخ فاکتور')),
                ('reference_number', models.CharField(max_length=80, verbose_name='شماره حواله')),
                ('attachment', models.FileField(upload_to='invoices/', verbose_name='فایل فاکتور')),
                ('customer_note', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('customer_note_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین بروزرسانی یادداشت')),
                ('customer_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان مشاهده مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_records', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_invoice_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فاکتور مشتری',
                'verbose_name_plural': 'فاکتورهای مشتری',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
