# Generated by Django 6.0.2 on 2026-04-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_invoicerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerecord',
            name='customer_visible_note',
            field=models.TextField(blank=True, verbose_name='توضیحات قابل مشاهده برای مشتری'),
        ),
        migrations.AddField(
            model_name='invoicerecord',
            name='internal_note',
            field=models.TextField(blank=True, verbose_name='توضیحات داخلی'),
        ),
    ]
