# Generated by Django 6.0.2 on 2026-04-28 22:29

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_invoicerecord_customer_visible_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_from',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ آغاز فعالیت'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره همراه'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='province',
            field=models.CharField(blank=True, max_length=50, verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='valid_until',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ اعتبار'),
        ),
    ]
