# Generated by Django 6.0.2 on 2026-04-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_userprofile_active_from_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='suspended',
            field=models.BooleanField(default=False, verbose_name='معلق'),
        ),
    ]
