# Generated by Django 6.0.2 on 2026-04-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='customer_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان مشاهده مشتری'),
        ),
    ]
