# Generated by Django 6.0.2 on 2026-04-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_paymentrecord_customer_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerecord',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='شماره فاکتور'),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='reference_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='شماره حواله'),
        ),
    ]
