# Generated by Django 6.0.2 on 2026-05-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_invoicerecord_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_view_invoices',
            field=models.BooleanField(default=False, verbose_name='دسترسی مشاهده فاکتورها'),
        ),
        migrations.AlterField(
            model_name='paymentactivitylog',
            name='action',
            field=models.CharField(choices=[('created', 'ایجاد'), ('edited', 'ویرایش'), ('status_changed', 'تغییر وضعیت'), ('viewed', 'رویت'), ('password_viewed', 'مشاهده رمز عبور')], max_length=20),
        ),
    ]
