# Generated by Django 6.0.2 on 2026-05-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_userprofile_can_view_invoices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_upload_invoices',
            field=models.BooleanField(default=False, verbose_name='دسترسی بارگذاری فاکتورها'),
        ),
    ]
