# Generated by Django 6.0.2 on 2026-05-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_userprofile_can_upload_invoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerecord',
            name='invoice_number',
            field=models.CharField(max_length=80, verbose_name='شماره فاکتور'),
        ),
    ]
