# Generated by Django 6.0.2 on 2026-05-06 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_alter_invoicerecord_invoice_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_created', 'ایجاد کاربر'), ('user_updated', 'ویرایش کاربر'), ('password_reset', 'ریست رمز عبور')], max_length=40, verbose_name='عملیات')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_system_logs', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لاگ عملیات سیستم',
                'verbose_name_plural': 'لاگ\u200cهای عملیات سیستم',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
