# Generated by Django 6.0.2 on 2026-05-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_systemactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentactivitylog',
            name='action',
            field=models.CharField(choices=[('created', 'ایجاد'), ('edited', 'ویرایش'), ('status_changed', 'تغییر وضعیت'), ('viewed', 'رویت')], max_length=20),
        ),
    ]
