# Generated by Django 6.0.2 on 2026-05-10 12:00

from django.db import migrations, models
import django_jalali.db.models as jmodels


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0028_alter_paymentactivitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerecord',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='invoice_date',
            field=jmodels.jDateField(blank=True, null=True, verbose_name='تاریخ فاکتور'),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='شماره فاکتور'),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='reference_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='شماره حواله'),
        ),
    ]
