# Generated by Django 6.0.2 on 2026-05-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0030_userprofile_second_contact_and_profile_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='توضیحات یا نکات مشتری در مورد این واریزی', verbose_name='توضیحات مشتری'),
        ),
    ]
