# Generated by Django 6.0.2 on 2026-05-17 02:18

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0031_paymentrecord_customer_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPaymentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_amount', models.BigIntegerField(verbose_name='مبلغ مورد انتظار')),
                ('note', models.TextField(blank=True, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_payment_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تخصیص واریز روزانه',
                'verbose_name_plural': 'تخصیص های واریز روزانه',
                'ordering': ['customer__first_name', 'customer__last_name', 'customer__username'],
            },
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='daily_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.dailypaymentassignment'),
        ),
        migrations.CreateModel(
            name='DailyPaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_date', django_jalali.db.models.jDateField(verbose_name='تاریخ واریز')),
                ('bank_name', models.CharField(blank=True, max_length=64, verbose_name='نام بانک')),
                ('account_number', models.CharField(max_length=64, verbose_name='شماره حساب مقصد')),
                ('account_owner', models.CharField(blank=True, max_length=128, verbose_name='نام صاحب حساب')),
                ('total_expected_amount', models.BigIntegerField(default=0, verbose_name='مبلغ کل مورد انتظار')),
                ('note', models.TextField(blank=True, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_payment_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'برنامه واریز روزانه',
                'verbose_name_plural': 'برنامه های واریز روزانه',
                'ordering': ['-deposit_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='dailypaymentassignment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='payments.dailypaymentplan'),
        ),
        migrations.AddConstraint(
            model_name='dailypaymentassignment',
            constraint=models.UniqueConstraint(fields=('plan', 'customer'), name='uniq_daily_payment_assignment_customer'),
        ),
    ]
