# Generated by Django 6.0.2 on 2026-05-17 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0032_dailypaymentassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_max_upload_size_mb', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='حداکثر حجم هر فایل فیش (مگابایت)')),
                ('invoice_max_upload_size_mb', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='حداکثر حجم فایل فاکتور (مگابایت)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات بارگذاری فایل',
                'verbose_name_plural': 'تنظیمات بارگذاری فایل',
            },
        ),
    ]
