# Generated by Django 6.0.2 on 2026-05-19 09:40

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0033_uploadsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='pay_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ واریز'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
