# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0034_alter_paymentrecord_amount_alter_paymentrecord_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                choices=[
                    ('customer', 'مشتری'),
                    ('finance', 'واحد مالی'),
                    ('commercial', 'واحد بازرگانی'),
                    ('sales', 'فروش'),
                    ('data_entry', 'تکمیل اطلاعات فیش'),
                    ('staff', 'کارمند'),
                ],
                default='customer',
                max_length=10,
                verbose_name='نوع کاربر',
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_payment_details',
            field=models.BooleanField(default=False, verbose_name='دسترسی تکمیل اطلاعات فیش‌ها'),
        ),
    ]
