# Generated by Django 6.0.2 on 2026-05-21 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0037_usernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='عنوان')),
                ('file', models.FileField(upload_to='price_lists/', verbose_name='فایل لیست قیمت')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات داخلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_price_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لیست قیمت',
                'verbose_name_plural': 'لیست قیمت\u200cها',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
