# Generated by Django 6.0.2 on 2026-05-21 09:32

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0038_pricelist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='عنوان')),
                ('valid_until', django_jalali.db.models.jDateField(verbose_name='اعتبار تا')),
                ('file', models.FileField(upload_to='proformas/', verbose_name='فایل پیش فاکتور')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات داخلی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید مشتری'), ('approved', 'تایید شده توسط مشتری')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان صدور')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proforma_invoices', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_proforma_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیش فاکتور',
                'verbose_name_plural': 'پیش فاکتورها',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProformaInvoiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('viewed', 'مشاهده'), ('file_viewed', 'مشاهده فایل'), ('approved', 'تایید مشتری')], max_length=20, verbose_name='عملیات')),
                ('note', models.TextField(blank=True, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_logs', to=settings.AUTH_USER_MODEL)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.proformainvoice')),
            ],
            options={
                'verbose_name': 'لاگ پیش فاکتور',
                'verbose_name_plural': 'لاگ\u200cهای پیش فاکتور',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
