# Generated by Django 6.0.2 on 2026-05-22 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0039_proformainvoice_proformainvoicelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('preview', 'پیش نمایش فرم'), ('invoice', 'فاکتور ثبت شده')], default='preview', max_length=20, verbose_name='منبع')),
                ('file', models.FileField(upload_to='invoice_extractions/', verbose_name='فایل پردازش')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='نام فایل اصلی')),
                ('file_kind', models.CharField(blank=True, max_length=30, verbose_name='نوع فایل')),
                ('text_source', models.CharField(blank=True, max_length=30, verbose_name='منبع متن')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پردازش'), ('queued', 'در صف پردازش'), ('processing', 'در حال پردازش'), ('done', 'پردازش شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('queue_job_id', models.CharField(blank=True, max_length=120, verbose_name='شناسه صف')),
                ('result_json', models.JSONField(blank=True, default=dict, verbose_name='خروجی JSON')),
                ('raw_text', models.TextField(blank=True, verbose_name='متن خام استخراج شده')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='هشدارها')),
                ('error_message', models.TextField(blank=True, verbose_name='خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('queued_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ورود به صف')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to='payments.invoicerecord')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_extraction_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پردازش خواندن فاکتور',
                'verbose_name_plural': 'پردازش\u200cهای خواندن فاکتور',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
