# Generated by Django 6.0.2 on 2026-05-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0040_invoiceextractionjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceextractionjob',
            name='queue_job_id',
        ),
        migrations.RemoveField(
            model_name='invoiceextractionjob',
            name='queued_at',
        ),
        migrations.AlterField(
            model_name='invoiceextractionjob',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پردازش'), ('processing', 'در حال پردازش'), ('done', 'پردازش شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
