# Generated by Django 6.0.2 on 2026-05-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0043_pricelist_proforma_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('commercial_review', 'بررسی بازرگانی'), ('finance_review', 'ثبت مالی'), ('approved', 'ثبت بازرگانی'), ('final_approved', 'تایید نهایی'), ('rejected', 'رد شده'), ('incomplete', 'ناقص'), ('returned_commercial', 'عودت به بازرگانی')], default='pending', max_length=20),
        ),
    ]
