# Generated by Django 6.0.2 on 2026-05-26 16:58

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0045_profilechangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceextractionjob',
            name='file',
            field=models.FileField(upload_to=payments.models.invoice_extraction_upload_to, verbose_name='فایل پردازش'),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='attachment',
            field=models.FileField(upload_to=payments.models.invoice_attachment_upload_to, verbose_name='فایل فاکتور'),
        ),
        migrations.AlterField(
            model_name='loginadvertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=payments.models.login_ad_upload_to, verbose_name='تصویر بنر'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='image',
            field=models.FileField(upload_to=payments.models.payment_receipt_upload_to),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to=payments.models.payment_record_receipt_upload_to),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='file',
            field=models.FileField(upload_to=payments.models.price_list_upload_to, verbose_name='فایل لیست قیمت'),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='file',
            field=models.FileField(upload_to=payments.models.proforma_upload_to, verbose_name='فایل پیش فاکتور'),
        ),
    ]
