# Generated by Django 6.0.2 on 2026-05-26 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0046_alter_invoiceextractionjob_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'ثبت شده'), ('reviewing', 'در حال بررسی فروش'), ('proforma_sent', 'پیش فاکتور صادر شده'), ('completed', 'خاتمه یافته'), ('cancelled', 'لغو شده')], default='submitted', max_length=20, verbose_name='وضعیت')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='عنوان سفارش')),
                ('customer_note', models.TextField(blank=True, verbose_name='توضیح مشتری')),
                ('staff_note', models.TextField(blank=True, verbose_name='توضیح داخلی فروش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('requested_sales_expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس فروش انتخابی مشتری')),
                ('sales_expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس فروش')),
            ],
            options={
                'verbose_name': 'سفارش مشتری',
                'verbose_name_plural': 'سفارش های مشتریان',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas', to='payments.customerorder', verbose_name='سفارش مرتبط'),
        ),
        migrations.CreateModel(
            name='CustomerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180, verbose_name='نام کالا')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='تعداد')),
                ('unit', models.CharField(choices=[('piece', 'قطعه'), ('pack', 'بسته'), ('carton', 'کارتن')], default='piece', max_length=20, verbose_name='واحد')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.customerorder')),
            ],
            options={
                'verbose_name': 'قلم سفارش',
                'verbose_name_plural': 'اقلام سفارش',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'ثبت سفارش'), ('status_changed', 'تغییر وضعیت'), ('assigned', 'تخصیص کارشناس'), ('proforma_created', 'صدور پیش فاکتور')], max_length=30, verbose_name='عملیات')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='وضعیت قبلی')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='وضعیت جدید')),
                ('note', models.TextField(blank=True, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_logs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.customerorder')),
            ],
            options={
                'verbose_name': 'لاگ سفارش',
                'verbose_name_plural': 'لاگ های سفارش',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSalesAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='تخصیص دهنده')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_assignment', to=settings.AUTH_USER_MODEL)),
                ('sales_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس فروش')),
            ],
            options={
                'verbose_name': 'تخصیص کارشناس فروش',
                'verbose_name_plural': 'تخصیص کارشناسان فروش',
                'ordering': ['customer__username'],
            },
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['customer', '-created_at'], name='payments_cu_custome_c1f359_idx'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['sales_expert', 'status'], name='payments_cu_sales_e_d83873_idx'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['status', '-created_at'], name='payments_cu_status_126757_idx'),
        ),
    ]
