# Generated by Django 6.0.2 on 2026-05-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0047_customerorder_proformainvoice_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'مشتری'), ('finance', 'واحد مالی'), ('finance_manager', 'مدیر مالی'), ('commercial', 'واحد بازرگانی'), ('commercial_manager', 'مدیر بازرگانی'), ('sales', 'فروش'), ('sales_manager', 'مدیر فروش'), ('data_entry', 'تکمیل اطلاعات فیش'), ('staff', 'کارمند')], default='customer', max_length=24, verbose_name='نوع کاربر'),
        ),
    ]
