# Generated by Django 6.0.2 on 2026-05-31 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0049_user_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_inactivity_timeout', models.PositiveIntegerField(default=30, help_text='پس از این مدت بی\u200cفعالیت، کاربر به\u200cصورت خودکار خارج می\u200cشود.', verbose_name='مدت بی\u200cفعالیت (دقیقه)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سیستم',
                'verbose_name_plural': 'تنظیمات سیستم',
            },
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='کلید نشست')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('x_forwarded_for', models.TextField(blank=True, help_text='ممکن است شامل آدرس\u200cهای شبکه داخلی باشد', verbose_name='زنجیره X-Forwarded-For')),
                ('user_agent_raw', models.TextField(blank=True, verbose_name='User-Agent خام')),
                ('browser_family', models.CharField(blank=True, max_length=100, verbose_name='مرورگر')),
                ('browser_version', models.CharField(blank=True, max_length=50, verbose_name='نسخه مرورگر')),
                ('os_family', models.CharField(blank=True, max_length=100, verbose_name='سیستم\u200cعامل')),
                ('os_version', models.CharField(blank=True, max_length=50, verbose_name='نسخه سیستم\u200cعامل')),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'رایانه'), ('mobile', 'موبایل'), ('tablet', 'تبلت'), ('bot', 'ربات')], default='desktop', max_length=10, verbose_name='نوع دستگاه')),
                ('device_brand', models.CharField(blank=True, max_length=100, verbose_name='برند دستگاه')),
                ('device_model', models.CharField(blank=True, max_length=100, verbose_name='مدل دستگاه')),
                ('accept_language', models.CharField(blank=True, max_length=200, verbose_name='زبان مرورگر')),
                ('login_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ورود')),
                ('logout_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج')),
                ('logout_reason', models.CharField(blank=True, choices=[('manual', 'خروج دستی'), ('inactivity', 'انقضای بی\u200cفعالیت'), ('forced', 'ورود از دستگاه دیگر')], max_length=20, verbose_name='دلیل خروج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_records', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سابقه ورود',
                'verbose_name_plural': 'سوابق ورود',
                'ordering': ['-login_at'],
            },
        ),
    ]
