# Generated by Django 6.0.2 on 2026-05-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0050_login_record_system_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accounting_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='کد تفضیلی'),
        ),
    ]
