# Generated by Django 6.0.2 on 2026-05-31 18:04

from django.db import migrations, models


def convert_unit_codes(apps, schema_editor):
    CustomerOrderItem = apps.get_model('payments', 'CustomerOrderItem')
    mapping = {'piece': 'قطعه', 'pack': 'بسته', 'carton': 'کارتن'}
    for item in CustomerOrderItem.objects.filter(unit__in=mapping.keys()):
        item.unit = mapping[item.unit]
        item.save(update_fields=['unit'])


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0051_accounting_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('product_code', models.CharField(blank=True, max_length=50, verbose_name='کد کالا')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد')),
                ('coefficient', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='ضریب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کاتالوگ کالاها',
                'ordering': ['product_name'],
            },
        ),
        migrations.AlterField(
            model_name='customerorderitem',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='واحد'),
        ),
        migrations.RunPython(convert_unit_codes, migrations.RunPython.noop),
    ]
