# Generated by Django 6.0.2 on 2026-05-31 19:46

from django.db import migrations, models


PAYMENT_FIELDS = [
    ('amount',                   'مبلغ واریزی'),
    ('pay_date',                 'تاریخ واریز'),
    ('tracking_code',            'شماره پیگیری'),
    ('payer_full_name',          'نام واریز کننده'),
    ('payer_account_number',     'شماره حساب واریز کننده'),
    ('payer_bank_name',          'بانک واریز کننده'),
    ('beneficiary_bank_name',    'بانک مقصد'),
    ('beneficiary_account_number', 'شماره حساب مقصد'),
    ('beneficiary_account_owner', 'صاحب حساب مقصد'),
]


def populate_initial_configs(apps, schema_editor):
    FieldRequirementConfig = apps.get_model('payments', 'FieldRequirementConfig')
    for field_name, field_label in PAYMENT_FIELDS:
        FieldRequirementConfig.objects.get_or_create(
            form_name='payment',
            field_name=field_name,
            defaults={'field_label': field_label, 'is_required': False},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0052_product_catalog_free_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderlog',
            name='action',
            field=models.CharField(choices=[('created', 'ثبت سفارش'), ('status_changed', 'تغییر وضعیت'), ('assigned', 'تخصیص کارشناس'), ('proforma_created', 'صدور پیش فاکتور'), ('proforma_approved', 'تایید پیش فاکتور توسط مشتری')], max_length=30, verbose_name='عملیات'),
        ),
        migrations.CreateModel(
            name='FieldRequirementConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(choices=[('payment', 'فرم ثبت فیش واریزی')], max_length=50, verbose_name='فرم')),
                ('field_name', models.CharField(max_length=100, verbose_name='نام فنی فیلد')),
                ('field_label', models.CharField(max_length=200, verbose_name='نام نمایشی فیلد')),
                ('is_required', models.BooleanField(default=False, verbose_name='ضروری (اجباری)')),
            ],
            options={
                'verbose_name': 'تنظیم اجباری بودن فیلد',
                'verbose_name_plural': 'تنظیمات اجباری بودن فیلدها',
                'ordering': ['form_name', 'field_name'],
                'unique_together': {('form_name', 'field_name')},
            },
        ),
        migrations.RunPython(populate_initial_configs, migrations.RunPython.noop),
    ]
