# Generated by Django 6.0.2 on 2026-05-31 19:56

from django.db import migrations, models


ALL_FORM_FIELDS = {
    'order': [
        ('title',         'عنوان سفارش',          True),
        ('customer_note', 'توضیحات سفارش',         False),
    ],
    'order_item': [
        ('product_name', 'نام کالا',            True),
        ('quantity',     'تعداد',               False),
        ('unit',         'واحد',                False),
        ('note',         'توضیح / کد کالا',     False),
    ],
    'profile': [
        ('email',          'ایمیل',              False),
        ('phone',          'شماره تلفن',          False),
        ('second_mobile',  'شماره همراه دوم',     False),
        ('organization',   'نام مجموعه',          False),
        ('address',        'آدرس',               False),
        ('second_address', 'آدرس دوم',            False),
    ],
    'payment_staff': [
        ('payer_full_name',           'نام واریز کننده',          True),
        ('payer_account_number',      'شماره حساب واریز کننده',   True),
        ('payer_bank_name',           'بانک واریز کننده',         True),
        ('beneficiary_bank_name',     'بانک مقصد',               True),
        ('beneficiary_account_number','شماره حساب مقصد',          True),
        ('beneficiary_account_owner', 'صاحب حساب مقصد',          True),
        ('amount',                    'مبلغ',                    True),
        ('tracking_code',             'کد پیگیری',               True),
        ('pay_date',                  'تاریخ واریز',              False),
    ],
    'order_proforma': [
        ('title',       'عنوان پیش فاکتور', False),
        ('valid_until', 'اعتبار تا',        True),
        ('note',        'توضیح داخلی',      False),
    ],
}


def populate_form_configs(apps, schema_editor):
    FieldRequirementConfig = apps.get_model('payments', 'FieldRequirementConfig')
    for form_name, fields in ALL_FORM_FIELDS.items():
        for field_name, field_label, is_required in fields:
            FieldRequirementConfig.objects.get_or_create(
                form_name=form_name,
                field_name=field_name,
                defaults={'field_label': field_label, 'is_required': is_required},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0053_field_requirement_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldrequirementconfig',
            name='form_name',
            field=models.CharField(choices=[('payment', 'فرم ثبت فیش واریزی'), ('order', 'فرم ثبت سفارش'), ('order_item', 'فرم اقلام سفارش'), ('profile', 'فرم ویرایش مشخصات مشتری'), ('payment_staff', 'فرم تکمیل اطلاعات فیش (کارمند)'), ('order_proforma', 'فرم صدور پیش فاکتور')], max_length=50, verbose_name='فرم'),
        ),
        migrations.RunPython(populate_form_configs, migrations.RunPython.noop),
    ]
