# Generated by Django 6.0.2 on 2026-05-31 20:02

from django.db import migrations, models


def copy_defaults_and_reset(apps, schema_editor):
    """مقدار is_required فعلی را به default_required کپی کرده، سپس is_required را None می‌کند."""
    FieldRequirementConfig = apps.get_model('payments', 'FieldRequirementConfig')
    for obj in FieldRequirementConfig.objects.all():
        obj.default_required = bool(obj.is_required)
        obj.is_required = None  # برگشت به حالت «استفاده از پیشفرض»
        obj.save(update_fields=['default_required', 'is_required'])


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0054_field_req_all_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldrequirementconfig',
            name='default_required',
            field=models.BooleanField(default=False, editable=False, help_text='مقدار پیشفرض تعریف\u200cشده در کد — فقط\u200cخواندنی', verbose_name='پیشفرض کد'),
        ),
        migrations.AlterField(
            model_name='fieldrequirementconfig',
            name='is_required',
            field=models.BooleanField(blank=True, help_text='خالی = استفاده از پیشفرض | بله = اجباری | خیر = اختیاری', null=True, verbose_name='تنظیم ادمین'),
        ),
        migrations.RunPython(copy_defaults_and_reset, migrations.RunPython.noop),
    ]
