# Generated by Django 6.0.2 on 2026-06-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0055_field_req_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentactivitylog',
            name='action',
            field=models.CharField(choices=[('created', 'ایجاد'), ('edited', 'ویرایش'), ('status_changed', 'تغییر وضعیت'), ('viewed', 'رویت'), ('customer_note', 'توضیح مشتری')], max_length=20),
        ),
    ]
