# Generated by Django 6.0.2 on 2026-06-01 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0056_customer_note_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='user',
            field=models.OneToOneField(blank=True, help_text='کاربری که به نام این طرف حساب وارد سیستم می\u200cشود', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_account', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری ورود'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='counterparty_approved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان تایید طرف حساب'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='counterparty_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_approvals', to=settings.AUTH_USER_MODEL, verbose_name='تایید شده توسط طرف حساب'),
        ),
        migrations.AlterField(
            model_name='paymentactivitylog',
            name='action',
            field=models.CharField(choices=[('created', 'ایجاد'), ('edited', 'ویرایش'), ('status_changed', 'تغییر وضعیت'), ('viewed', 'رویت'), ('customer_note', 'توضیح مشتری'), ('cp_approved', 'تایید طرف حساب'), ('cp_returned', 'بازگشت از طرف حساب')], max_length=20),
        ),
    ]
