# Generated by Django 6.0.2 on 2026-06-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0057_counterparty_user_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='status',
            field=models.CharField(choices=[('active', 'فعال — ورود و عملیات مجاز'), ('inactive', 'غیرفعال — ورود مجاز، عملیات ممنوع'), ('suspended', 'معلق — ورود ممنوع')], default='active', max_length=20, verbose_name='وضعیت'),
        ),
    ]
