# Generated by Django 6.0.2 on 2026-06-01 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0058_counterparty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='نام سازمان / طرف حساب'),
        ),
        migrations.CreateModel(
            name='CounterpartyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=80, verbose_name='نام بانک')),
                ('city', models.CharField(blank=True, max_length=60, verbose_name='شهر')),
                ('branch', models.CharField(blank=True, max_length=100, verbose_name='شعبه')),
                ('account_number', models.CharField(blank=True, max_length=30, verbose_name='شماره حساب')),
                ('account_owner', models.CharField(blank=True, max_length=120, verbose_name='نام صاحب حساب')),
                ('iban', models.CharField(blank=True, help_text='IR + 24 رقم', max_length=30, verbose_name='شماره شبا')),
                ('is_primary', models.BooleanField(default=False, verbose_name='حساب اصلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='payments.counterparty', verbose_name='طرف حساب')),
            ],
            options={
                'verbose_name': 'حساب بانکی طرف حساب',
                'verbose_name_plural': 'حساب\u200cهای بانکی طرف حساب',
                'ordering': ['-is_primary', 'bank_name'],
            },
        ),
    ]
