# Generated by Django 6.0.2 on 2026-06-01 09:50

from django.db import migrations, models

NEW_CONFIGS = {
    'counterparty': [
        ('name',        'نام سازمان',    True),
        ('first_name',  'نام',            False),
        ('last_name',   'نام خانوادگی',  False),
        ('phone',       'شماره تماس',     False),
        ('description', 'توضیحات',       False),
    ],
    'counterparty_bank': [
        ('bank_name',      'نام بانک',          False),
        ('city',           'شهر',                False),
        ('branch',         'شعبه',               False),
        ('account_number', 'شماره حساب',         False),
        ('account_owner',  'صاحب حساب',          False),
        ('iban',           'شماره شبا',           False),
    ],
}


def populate_counterparty_configs(apps, schema_editor):
    FRC = apps.get_model('payments', 'FieldRequirementConfig')
    for form_name, fields in NEW_CONFIGS.items():
        for field_name, field_label, is_required in fields:
            FRC.objects.get_or_create(
                form_name=form_name,
                field_name=field_name,
                defaults={'field_label': field_label, 'default_required': is_required, 'is_required': None},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0059_counterparty_personal_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldrequirementconfig',
            name='form_name',
            field=models.CharField(choices=[('payment', 'فرم ثبت فیش واریزی'), ('order', 'فرم ثبت سفارش'), ('order_item', 'فرم اقلام سفارش'), ('profile', 'فرم ویرایش مشخصات مشتری'), ('payment_staff', 'فرم تکمیل اطلاعات فیش (کارمند)'), ('order_proforma', 'فرم صدور پیش فاکتور'), ('counterparty', 'فرم طرف حساب'), ('counterparty_bank', 'فرم حساب بانکی طرف حساب')], max_length=50, verbose_name='فرم'),
        ),
        migrations.RunPython(populate_counterparty_configs, migrations.RunPython.noop),
    ]
