# Generated by Django 6.0.2 on 2026-06-01

from django.db import migrations

CONFIGS = {
    'counterparty': [
        ('name',        'نام سازمان',    True),
        ('first_name',  'نام',            False),
        ('last_name',   'نام خانوادگی',  False),
        ('phone',       'شماره تماس',     False),
        ('description', 'توضیحات',       False),
    ],
    'counterparty_bank': [
        ('bank_name',      'نام بانک',       False),
        ('city',           'شهر',             False),
        ('branch',         'شعبه',            False),
        ('account_number', 'شماره حساب',      False),
        ('account_owner',  'صاحب حساب',       False),
        ('iban',           'شماره شبا',        False),
    ],
}


def populate(apps, schema_editor):
    FRC = apps.get_model('payments', 'FieldRequirementConfig')
    for form_name, fields in CONFIGS.items():
        for field_name, field_label, is_req in fields:
            FRC.objects.get_or_create(
                form_name=form_name,
                field_name=field_name,
                defaults={'field_label': field_label, 'default_required': is_req, 'is_required': None},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0060_counterparty_form_config'),
    ]

    operations = [
        migrations.RunPython(populate, migrations.RunPython.noop),
    ]
