# Generated by Django 6.0.2 on 2026-06-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0061_counterparty_configs_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'مشتری'), ('commercial', 'واحد بازرگانی'), ('commercial_manager', 'مدیر بازرگانی'), ('finance', 'واحد مالی'), ('finance_manager', 'مدیر مالی'), ('sales', 'فروش'), ('sales_manager', 'مدیر فروش'), ('data_entry', 'تکمیل اطلاعات فیش'), ('staff', 'کارمند'), ('counterparty', 'طرف حساب')], default='customer', max_length=24, verbose_name='نوع کاربر'),
        ),
    ]
