# Generated by Django 6.0.2 on 2026-06-01 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0062_add_counterparty_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='counterparty_decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تصمیم طرف حساب'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='counterparty_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_decisions', to=settings.AUTH_USER_MODEL, verbose_name='تصمیم\u200cگیرنده طرف حساب'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='counterparty_note',
            field=models.TextField(blank=True, verbose_name='توضیح طرف حساب'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='counterparty_status',
            field=models.CharField(blank=True, choices=[('cp_approved', 'تایید شده'), ('cp_returned', 'عودت / ناقص'), ('cp_rejected', 'رد / ابطال')], db_index=True, max_length=20, null=True, verbose_name='وضعیت طرف حساب'),
        ),
        migrations.AlterField(
            model_name='paymentactivitylog',
            name='action',
            field=models.CharField(choices=[('created', 'ایجاد'), ('edited', 'ویرایش'), ('status_changed', 'تغییر وضعیت'), ('viewed', 'رویت'), ('customer_note', 'توضیح مشتری'), ('cp_approved', 'تایید طرف حساب'), ('cp_returned', 'عودت/ناقص از طرف حساب'), ('cp_rejected', 'رد/ابطال توسط طرف حساب')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='counterparty_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید (قدیمی)'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='counterparty_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_approvals', to=settings.AUTH_USER_MODEL, verbose_name='تایید شده توسط (قدیمی)'),
        ),
    ]
