# Generated by Django 6.0.2 on 2026-06-01 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0063_cp_decision_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='finance_registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت مالی'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='finance_registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_registrations', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده مالی'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='finance_status',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='وضعیت مالی'),
        ),
    ]
