# Generated by Django 6.0.2 on 2026-06-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0064_finance_status_independent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentactivitylog',
            name='action',
            field=models.CharField(choices=[('created', 'ثبت سند'), ('edited', 'ویرایش سند'), ('status_changed', 'تغییر وضعیت بازرگانی'), ('viewed', 'مشاهده'), ('customer_note', 'توضیح مشتری'), ('finance_reg', 'ثبت مالی'), ('final_approved', 'تأیید نهایی'), ('cp_approved', 'تایید طرف حساب'), ('cp_returned', 'عودت/ناقص از طرف حساب'), ('cp_rejected', 'رد/ابطال توسط طرف حساب')], max_length=20),
        ),
    ]
