# Generated by Django 6.0.2 on 2026-06-02 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0065_timeline_actions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='final_approval_delegated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_final_approvals', to=settings.AUTH_USER_MODEL, verbose_name='تفویض تأیید نهایی به'),
        ),
    ]
