# Generated by Django 6.0.2 on 2026-06-02 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0066_final_approval_delegate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecord',
            name='final_approval_delegated_to',
        ),
        migrations.CreateModel(
            name='FinalApprovalDelegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('note', models.TextField(blank=True, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('delegated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_approval_delegations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر تفویض\u200cشده')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_delegations', to=settings.AUTH_USER_MODEL, verbose_name='تفویض\u200cکننده')),
            ],
            options={
                'verbose_name': 'تفویض تأیید نهایی',
                'verbose_name_plural': 'تفویض\u200cهای تأیید نهایی',
                'unique_together': {('delegated_user',)},
            },
        ),
    ]
