# Generated by Django 6.0.2 on 2026-06-02 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0067_final_approval_delegate_global'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=20, verbose_name='گیرنده')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('purpose', models.CharField(blank=True, max_length=40, verbose_name='هدف')),
                ('status', models.CharField(choices=[('sent', 'ارسال شد'), ('failed', 'خطا')], max_length=10, verbose_name='وضعیت')),
                ('provider', models.CharField(blank=True, max_length=20, verbose_name='اپراتور')),
                ('error', models.TextField(blank=True, verbose_name='خطا')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'لاگ پیامک',
                'verbose_name_plural': 'لاگ پیامک\u200cها',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=256, verbose_name='کلید API پیامک'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_generic_extra',
            field=models.JSONField(blank=True, default=dict, help_text='JSON اضافی که به body درخواست اضافه می\u200cشود (مثلاً username/password)', verbose_name='پارامترهای اضافه API'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_generic_url',
            field=models.URLField(blank=True, help_text='فقط برای نوع HTTP عمومی — آدرس endpoint ارسال پیامک', verbose_name='آدرس API پیامک عمومی'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=False, verbose_name='اطلاع\u200cرسانی پیامکی فعال'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_otp_expiry_minutes',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='اعتبار کد OTP (دقیقه)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_otp_template',
            field=models.CharField(default='کد تأیید سامانه: {code}\nاعتبار: {minutes} دقیقه', help_text='متغیرهای مجاز: {code}, {minutes}', max_length=200, verbose_name='قالب پیام OTP'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_provider',
            field=models.CharField(choices=[('disabled', 'غیرفعال'), ('kavenegar', 'کاوه\u200cنگار (Kavenegar)'), ('ghasedak', 'قاصدک (Ghasedak)'), ('generic', 'HTTP عمومی (سایر اپراتورها)')], default='disabled', max_length=20, verbose_name='اپراتور پیامک'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_sender',
            field=models.CharField(blank=True, help_text='شماره خط اختصاصی یا نام خط (بسته به اپراتور)', max_length=40, verbose_name='شماره فرستنده'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sms_mfa_enabled',
            field=models.BooleanField(default=False, verbose_name='ورود دو مرحله\u200cای با پیامک'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('commercial_review', 'بررسی بازرگانی'), ('approved', 'ثبت بازرگانی'), ('final_approved', 'تایید نهایی'), ('rejected', 'رد شده'), ('incomplete', 'ناقص'), ('returned_commercial', 'عودت به بازرگانی')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SMSOTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره گیرنده')),
                ('code', models.CharField(max_length=8, verbose_name='کد OTP')),
                ('purpose', models.CharField(choices=[('mfa', 'ورود دو مرحله\u200cای'), ('approval', 'تأیید عملیات')], default='mfa', max_length=20, verbose_name='هدف')),
                ('ref_id', models.CharField(blank=True, help_text='مثلاً شناسه سند برای تأیید از طریق پیامک', max_length=50, verbose_name='شناسه مرجع')),
                ('is_used', models.BooleanField(default=False, verbose_name='مصرف شده')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_otps', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کد OTP پیامکی',
                'verbose_name_plural': 'کدهای OTP پیامکی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used'], name='payments_sm_user_id_b262a1_idx')],
            },
        ),
    ]
