# Generated by Django 6.0.2 on 2026-06-05 20:06

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0068_sms_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to=payments.models.profile_avatar_upload_to, verbose_name='عکس نمایه'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_preset',
            field=models.CharField(choices=[('neutral_1', 'نمایه عمومی ۱'), ('neutral_2', 'نمایه عمومی ۲'), ('male_1', 'نمایه مرد ۱'), ('male_2', 'نمایه مرد ۲'), ('female_1', 'نمایه زن ۱'), ('female_2', 'نمایه زن ۲')], default='neutral_1', max_length=20, verbose_name='نمایه پیش\u200cفرض'),
        ),
    ]
