# Generated by Django 6.0.2 on 2026-06-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0069_userprofile_avatar_image_userprofile_avatar_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='delegate_sms_to_representative',
            field=models.BooleanField(default=False, verbose_name='ارسال پیامک به نماینده'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='representative_mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='موبایل نماینده'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='representative_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام نماینده'),
        ),
    ]
