# Generated by Django 6.0.2 on 2026-06-06 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0070_userprofile_delegate_sms_to_representative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_reconciliation',
            field=models.BooleanField(default=False, verbose_name='دسترسی مغایرت\u200cگیری'),
        ),
        migrations.CreateModel(
            name='ReconciliationThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان گفتگو')),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته')], default='open', max_length=12, verbose_name='وضعیت')),
                ('document_type', models.CharField(blank=True, choices=[('payment', 'فیش واریزی'), ('order', 'سفارش'), ('proforma', 'پیشنهاد فروش / پیش\u200cفاکتور'), ('invoice', 'فاکتور فروش'), ('daily_payment', 'برنامه واریز'), ('other', 'سایر')], default='other', max_length=24, verbose_name='نوع سند مرجع')),
                ('document_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه سند مرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reconciliation_threads', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_threads', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('staff_participants', models.ManyToManyField(related_name='assigned_reconciliation_threads', to=settings.AUTH_USER_MODEL, verbose_name='کارشناسان منتخب')),
            ],
            options={
                'verbose_name': 'گفتگوی مغایرت\u200cگیری',
                'verbose_name_plural': 'گفتگوهای مغایرت\u200cگیری',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='متن پیام')),
                ('document_type', models.CharField(blank=True, choices=[('payment', 'فیش واریزی'), ('order', 'سفارش'), ('proforma', 'پیشنهاد فروش / پیش\u200cفاکتور'), ('invoice', 'فاکتور فروش'), ('daily_payment', 'برنامه واریز'), ('other', 'سایر')], default='', max_length=24, verbose_name='نوع سند ارجاع\u200cشده')),
                ('document_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه سند ارجاع\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='payments.reconciliationthread', verbose_name='گفتگو')),
            ],
            options={
                'verbose_name': 'پیام مغایرت\u200cگیری',
                'verbose_name_plural': 'پیام\u200cهای مغایرت\u200cگیری',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
