# Generated by Django 6.0.2 on 2026-06-06 07:06

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0072_reconciliationreadstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='system_logo',
            field=models.ImageField(blank=True, help_text='فرمت مجاز: PNG/JPG/WEBP، حداکثر 512KB، حداکثر 600×220 پیکسل.', null=True, upload_to=payments.models.system_logo_upload_to, verbose_name='لوگوی سامانه'),
        ),
    ]
