# Generated by Django 6.0.2 on 2026-06-08 13:46

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0073_systemsettings_system_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=payments.models.reconciliation_attachment_upload_to, verbose_name='فایل پیوست'),
        ),
        migrations.AddField(
            model_name='reconciliationmessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام فایل پیوست'),
        ),
        migrations.AlterField(
            model_name='reconciliationmessage',
            name='body',
            field=models.TextField(blank=True, verbose_name='متن پیام'),
        ),
    ]
