# Generated by Django 6.0.2 on 2026-06-09 17:53

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def copy_locked_to_is_locked(apps, schema_editor):
    PaymentRecord = apps.get_model('payments', 'PaymentRecord')
    PaymentRecord.objects.filter(locked_by_finance=True).update(is_locked=True)


def backfill_pending_final(apps, schema_editor):
    PaymentRecord = apps.get_model('payments', 'PaymentRecord')
    now = timezone.now()
    for p in PaymentRecord.objects.filter(
        status='approved',
        finance_status='finance_ok',
    ).select_related():
        has_cp = p.counterparty_id is not None
        cp_ok = (not has_cp) or p.counterparty_status == 'cp_approved'
        if cp_ok:
            PaymentRecord.objects.filter(pk=p.pk).update(
                pending_final_approval=True,
                pending_final_approval_since=now,
            )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0074_reconciliationmessage_attachment_and_more'),
    ]

    operations = [
        # ابتدا is_locked اضافه می‌شود تا بتوان داده‌ها را کپی کرد
        migrations.AddField(
            model_name='paymentrecord',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='قفل پایانی'),
        ),
        # pending_final_approval اضافه می‌شود
        migrations.AddField(
            model_name='paymentrecord',
            name='pending_final_approval',
            field=models.BooleanField(db_index=True, default=False, verbose_name='در انتظار تأیید نهایی'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='pending_final_approval_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان آماده‌شدن برای تأیید نهایی'),
        ),
        # کپی داده‌های locked_by_finance → is_locked
        migrations.RunPython(copy_locked_to_is_locked, migrations.RunPython.noop),
        # پر کردن pending_final_approval برای سوابق موجود
        migrations.RunPython(backfill_pending_final, migrations.RunPython.noop),
        # حذف فیلدهای legacy
        migrations.RemoveField(
            model_name='paymentrecord',
            name='counterparty_approved_at',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='counterparty_approved_by',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='locked_by_finance',
        ),
    ]
