# Generated by Django 6.0.2 on 2026-06-09 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0075_flag_cleanup_pending_final'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='شماره موبایل')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='موبایل تأیید شده')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(blank=True, max_length=10, verbose_name='کد ملی')),
                ('province', models.CharField(max_length=50, verbose_name='استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('home_address', models.TextField(verbose_name='آدرس محل سکونت')),
                ('business_address', models.TextField(verbose_name='آدرس محل فعالیت')),
                ('activity_domain', models.CharField(max_length=100, verbose_name='حوزه فعالیت')),
                ('services_offered', models.TextField(verbose_name='خدمات قابل ارائه')),
                ('years_experience', models.PositiveSmallIntegerField(default=0, verbose_name='سابقه کاری (سال)')),
                ('has_business_license', models.BooleanField(default=False, verbose_name='جواز کسب دارم')),
                ('referrer_name', models.CharField(blank=True, max_length=100, verbose_name='نام معرف')),
                ('referrer_phone', models.CharField(blank=True, max_length=20, verbose_name='موبایل معرف')),
                ('motivation', models.TextField(blank=True, verbose_name='دلایل و انگیزه')),
                ('tracking_code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='کد پیگیری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewing', 'در حال بررسی'), ('info_needed', 'نیاز به اطلاعات تکمیلی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('staff_note', models.TextField(blank=True, verbose_name='یادداشت داخلی')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد')),
                ('info_request_note', models.TextField(blank=True, verbose_name='توضیح درخواست اطلاعات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_agency_apps', to=settings.AUTH_USER_MODEL, verbose_name='مسئول بررسی')),
                ('created_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_agency_application', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجادشده')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_agency_apps', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
            ],
            options={
                'verbose_name': 'درخواست نمایندگی',
                'verbose_name_plural': 'درخواست\u200cهای نمایندگی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'ارسال درخواست'), ('reviewing', 'شروع بررسی'), ('info_needed', 'درخواست اطلاعات تکمیلی'), ('approved', 'تأیید'), ('rejected', 'رد'), ('note', 'یادداشت'), ('assigned', 'تخصیص')], max_length=20, verbose_name='عملیات')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.agencyapplication')),
            ],
            options={
                'verbose_name': 'لاگ درخواست نمایندگی',
                'verbose_name_plural': 'لاگ\u200cهای درخواست نمایندگی',
                'ordering': ['created_at'],
            },
        ),
    ]
