# Generated by Django 6.0.2 on 2026-06-09 20:03

import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0076_agency_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencyapplicationlog',
            options={'verbose_name': 'لاگ درخواست نمایندگی', 'verbose_name_plural': 'لاگ\u200cهای درخواست نمایندگی'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'مشتری'), ('commercial', 'واحد بازرگانی'), ('commercial_manager', 'مدیر بازرگانی'), ('finance', 'واحد مالی'), ('finance_manager', 'مدیر مالی'), ('sales', 'فروش'), ('sales_manager', 'مدیر فروش'), ('data_entry', 'تکمیل اطلاعات فیش'), ('staff', 'کارمند'), ('warranty', 'کارشناس گارانتی'), ('warranty_manager', 'مدیر گارانتی'), ('counterparty', 'طرف حساب')], default='customer', max_length=24, verbose_name='نوع کاربر'),
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimant_name', models.CharField(max_length=100, verbose_name='نام متقاضی')),
                ('claimant_phone', models.CharField(max_length=20, verbose_name='موبایل متقاضی')),
                ('claimant_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('part_name', models.CharField(max_length=200, verbose_name='نام قطعه / محصول')),
                ('part_model', models.CharField(blank=True, max_length=200, verbose_name='مدل / شناسه')),
                ('serial_number', models.CharField(db_index=True, max_length=100, verbose_name='شماره سریال')),
                ('purchase_date', models.DateField(verbose_name='تاریخ خرید')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='شماره فاکتور')),
                ('defect_description', models.TextField(verbose_name='شرح خرابی')),
                ('customer_reply', models.TextField(blank=True, verbose_name='توضیح تکمیلی مشتری')),
                ('tracking_code', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='کد پیگیری')),
                ('status', models.CharField(choices=[('submitted', 'ثبت شده'), ('reviewing', 'در حال بررسی'), ('info_needed', 'نیاز به اطلاعات تکمیلی'), ('approved', 'تأیید گارانتی'), ('in_progress', 'در حال پردازش'), ('resolved', 'رفع شد'), ('rejected', 'رد شده'), ('closed', 'بسته شده')], db_index=True, default='submitted', max_length=20, verbose_name='وضعیت')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'معمولی'), ('high', 'زیاد'), ('urgent', 'فوری')], db_index=True, default='normal', max_length=10, verbose_name='اولویت')),
                ('resolution_type', models.CharField(blank=True, choices=[('repair', 'تعمیر'), ('replace', 'تعویض'), ('refund', 'استرداد وجه')], max_length=20, verbose_name='نوع رفع مسئله')),
                ('resolution_note', models.TextField(blank=True, verbose_name='توضیح رفع مسئله')),
                ('staff_note', models.TextField(blank=True, verbose_name='یادداشت داخلی')),
                ('info_request_note', models.TextField(blank=True, verbose_name='توضیح درخواست اطلاعات')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع بررسی')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ رفع')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='موعد پاسخ SLA')),
                ('customer_rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='امتیاز مشتری')),
                ('customer_feedback', models.TextField(blank=True, verbose_name='بازخورد مشتری')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_warranty_claims', to=settings.AUTH_USER_MODEL, verbose_name='مسئول بررسی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_claims', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست گارانتی',
                'verbose_name_plural': 'درخواست\u200cهای گارانتی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaimFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=payments.models.warranty_claim_file_upload_to, verbose_name='فایل')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='payments.warrantyclaim')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_claim_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فایل گارانتی',
                'verbose_name_plural': 'فایل\u200cهای گارانتی',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaimLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'ثبت درخواست'), ('reviewing', 'شروع بررسی'), ('info_needed', 'درخواست اطلاعات تکمیلی'), ('customer_reply', 'پاسخ مشتری'), ('approved', 'تأیید گارانتی'), ('in_progress', 'شروع پردازش'), ('resolved', 'رفع شد'), ('rejected', 'رد گارانتی'), ('closed', 'بسته شدن'), ('note', 'یادداشت'), ('assigned', 'تخصیص'), ('priority', 'تغییر اولویت'), ('file', 'بارگذاری فایل'), ('rated', 'ثبت امتیاز')], max_length=30, verbose_name='اقدام')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('is_visible_to_customer', models.BooleanField(default=True, verbose_name='قابل مشاهده توسط مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.warrantyclaim')),
            ],
            options={
                'verbose_name': 'لاگ گارانتی',
                'verbose_name_plural': 'لاگ\u200cهای گارانتی',
                'ordering': ['created_at'],
            },
        ),
    ]
