# Generated by Django 6.0.2 on 2026-06-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0078_warranty_add_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین ویرایش'),
        ),
    ]
