# Generated by Django 6.0.2 on 2026-06-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0079_payment_last_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('amount_mismatch', 'مغایرت مبلغ'), ('invalid_document', 'فیش/سند نامعتبر یا ناخوانا'), ('wrong_account', 'واریز به حساب اشتباه'), ('duplicate', 'تکراری بودن فیش'), ('defective_document', 'مخدوش بودن سند'), ('other', 'سایر')], db_index=True, max_length=30, verbose_name='دلیل رد'),
        ),
    ]
