# Generated by Django 6.0.2 on 2026-06-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0080_paymentrecord_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='customer_warranty_menu_enabled',
            field=models.BooleanField(default=False, help_text='در صورت فعال بودن، گزینه\u200cهای درخواست گارانتی، درخواست\u200cهای من و پیگیری وضعیت در منوی مشتریان نمایش داده می\u200cشود.', verbose_name='نمایش منوی «گارانتی و خدمات پس از فروش» برای مشتریان'),
        ),
    ]
