# Generated by Django 6.0.2 on 2026-06-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0081_systemsettings_customer_warranty_menu_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='accounting_code_import_enabled',
            field=models.BooleanField(default=False, help_text='در صورت غیرفعال بودن، این دکمه برای هیچ\u200cکس (حتی مدیران) در صفحه مشتریان نمایش داده نمی\u200cشود.', verbose_name='فعال بودن دکمه «ورود کد تفضیلی از اکسل» در صفحه مشتریان'),
        ),
    ]
