# Generated by Django 6.0.2 on 2026-06-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0083_paymentrecord_status_temp_commercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationmessage',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، این پیام از دید مشتری پنهان است.', verbose_name='فقط کارکنان'),
        ),
        migrations.AddField(
            model_name='reconciliationthread',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، این thread از دید مشتری پنهان است.', verbose_name='فقط کارکنان'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('commercial_review', 'بررسی بازرگانی'), ('temp_commercial', 'ثبت موقت بازرگانی'), ('approved', 'ثبت بازرگانی'), ('final_approved', 'تایید نهایی'), ('rejected', 'رد شده'), ('incomplete', 'ناقص'), ('returned_commercial', 'عودت به بازرگانی')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='session_inactivity_timeout',
            field=models.PositiveIntegerField(default=15, help_text='پس از این مدت بی\u200cفعالیت، کاربر به\u200cصورت خودکار خارج می\u200cشود.', verbose_name='مدت بی\u200cفعالیت (دقیقه)'),
        ),
    ]
