# Generated by Django 6.0.2 on 2026-06-18 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0085_reconciliationthread_customer_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان حذف'),
        ),
        migrations.AddField(
            model_name='reconciliationmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_reconciliation_messages', to=settings.AUTH_USER_MODEL, verbose_name='حذف\u200cکننده'),
        ),
        migrations.AddField(
            model_name='reconciliationmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ویرایش'),
        ),
        migrations.AddField(
            model_name='reconciliationmessage',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
        migrations.AddField(
            model_name='reconciliationmessage',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='ویرایش شده'),
        ),
        migrations.CreateModel(
            name='ReconciliationMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('edit', 'ویرایش'), ('delete', 'حذف')], max_length=16, verbose_name='عملیات')),
                ('old_body', models.TextField(blank=True, verbose_name='متن قبلی')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_message_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.reconciliationmessage', verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'لاگ پیام گفتگو',
                'verbose_name_plural': 'لاگ\u200cهای پیام گفتگو',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMessageReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان مشاهده')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='payments.reconciliationmessage', verbose_name='پیام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_read_receipts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رسید خواندن پیام',
                'verbose_name_plural': 'رسیدهای خواندن پیام',
                'ordering': ['read_at'],
                'unique_together': {('message', 'user')},
            },
        ),
    ]
