# Generated by Django 6.0.2 on 2026-06-18 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0086_reconciliation_message_edit_delete_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='payments.reconciliationmessage', verbose_name='در پاسخ به'),
        ),
    ]
