# Generated by Django 6.0.2 on 2026-06-18 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0087_reconciliationmessage_reply_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationmessagelog',
            name='action',
            field=models.CharField(choices=[('edit', 'ویرایش'), ('delete', 'حذف'), ('visibility', 'تغییر دیدپذیری')], max_length=16, verbose_name='عملیات'),
        ),
        migrations.CreateModel(
            name='ReconciliationThreadPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان پین')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='payments.reconciliationthread', verbose_name='گفتگو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_recon_threads', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گفتگوی پین\u200cشده',
                'verbose_name_plural': 'گفتگوهای پین\u200cشده',
                'ordering': ['-pinned_at'],
                'unique_together': {('user', 'thread')},
            },
        ),
    ]
