# Generated by Django 6.0.2 on 2026-06-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0088_reconciliationthreadpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='jitsi_server_url',
            field=models.CharField(blank=True, help_text='آدرس سرور Jitsi داخلی بدون https:// — مثال: meet.company.local یا 192.168.1.50:8443', max_length=255, verbose_name='آدرس سرور Jitsi Meet'),
        ),
        migrations.AlterField(
            model_name='reconciliationmessagelog',
            name='action',
            field=models.CharField(choices=[('edit', 'ویرایش'), ('delete', 'حذف'), ('visibility', 'تغییر دیدپذیری'), ('info', 'مشاهده اطلاعات')], max_length=16, verbose_name='عملیات'),
        ),
    ]
