# Generated by Django 6.0.2 on 2026-06-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0089_jitsi_server_url_in_system_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allow_multiple_sessions',
            field=models.BooleanField(default=True, help_text='اگر فعال باشد، کاربر می\u200cتواند همزمان از چند دستگاه/مرورگر وارد شود. اگر غیرفعال باشد، ورود از دستگاه جدید نشست قبلی را خاتمه می\u200cدهد.', verbose_name='اجازه ورود همزمان از چند دستگاه'),
        ),
    ]
