# Generated by Django 6.0.2 on 2026-06-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0090_allow_multiple_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='jitsi_call_enabled',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، دکمه تماس در صفحه گفتگو نمایش داده می\u200cشود.', verbose_name='نمایش دکمه تماس صوتی'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='jitsi_server_url',
            field=models.CharField(blank=True, help_text='آدرس سرور Jitsi بدون https:// — مثال: meet.company.local یا 192.168.1.50:8443', max_length=255, verbose_name='آدرس سرور Jitsi Meet'),
        ),
    ]
