# Generated by Django 6.0.2 on 2026-06-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0091_jitsi_call_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='multi_session_override',
            field=models.BooleanField(blank=True, default=None, help_text='خالی = پیروی از تنظیم سراسری | فعال = همیشه مجاز | غیرفعال = همیشه ممنوع', null=True, verbose_name='ورود از چند دستگاه'),
        ),
    ]
