# Generated by Django 6.0.2 on 2026-06-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0092_multi_session_override_on_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockedUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'کاربر قفل\u200cشده',
                'verbose_name_plural': 'کاربران قفل\u200cشده (axes)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.usersession',),
        ),
        migrations.AddField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین فعالیت'),
        ),
    ]
