# Generated by Django 6.0.2 on 2026-08-15 14:26

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0094_paymentrecord_manual_counterparty_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPaymentNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_date', django_jalali.db.models.jDateField(verbose_name='تاریخ اطلاعیه')),
                ('payment_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فیش\u200cها')),
                ('total_amount', models.BigIntegerField(default=0, verbose_name='جمع مبلغ فیش\u200cها')),
                ('message', models.TextField(blank=True, verbose_name='متن قابل نمایش برای مشتری')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='منتشر شده برای مشتری')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار')),
                ('customer_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان مشاهده مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_payment_notices', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_payment_notices', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_daily_payment_notices', to=settings.AUTH_USER_MODEL, verbose_name='منتشرکننده')),
            ],
            options={
                'verbose_name': 'اطلاعیه روزانه فیش مشتری',
                'verbose_name_plural': 'اطلاعیه\u200cهای روزانه فیش مشتریان',
                'ordering': ['-notice_date', '-updated_at', '-id'],
                'indexes': [models.Index(fields=['customer', 'is_published', '-notice_date'], name='payments_da_custome_a59023_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'notice_date'), name='uniq_daily_payment_notice_customer_date')],
            },
        ),
    ]
