# Generated by Codex on 2026-08-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_sales_user(apps, schema_editor):
    DailyPaymentAssignment = apps.get_model('payments', 'DailyPaymentAssignment')
    CustomerSalesAssignment = apps.get_model('payments', 'CustomerSalesAssignment')
    sales_by_customer = {
        item.customer_id: item.sales_user_id
        for item in CustomerSalesAssignment.objects.filter(sales_user__isnull=False)
    }
    assignments = DailyPaymentAssignment.objects.filter(sales_user__isnull=True)
    for assignment in assignments.iterator():
        sales_user_id = sales_by_customer.get(assignment.customer_id)
        if sales_user_id:
            assignment.sales_user_id = sales_user_id
            assignment.save(update_fields=['sales_user'])


def clear_sales_user(apps, schema_editor):
    DailyPaymentAssignment = apps.get_model('payments', 'DailyPaymentAssignment')
    DailyPaymentAssignment.objects.update(sales_user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0095_daily_payment_notice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypaymentassignment',
            name='sales_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='daily_payment_sales_assignments',
                to=settings.AUTH_USER_MODEL,
                verbose_name='کارشناس فروش',
            ),
        ),
        migrations.RunPython(populate_sales_user, clear_sales_user),
    ]
