# Generated by Django 6.0.2 on 2026-09-05 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0097_payment_workflow_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='void_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید ابطال'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='void_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='void_confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='تأیید\u200cکننده ابطال'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='void_reason',
            field=models.TextField(blank=True, verbose_name='دلیل ابطال'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ابطال'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_payments', to=settings.AUTH_USER_MODEL, verbose_name='ابطال\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='paymentactivitylog',
            name='action',
            field=models.CharField(choices=[('created', 'ثبت سند'), ('edited', 'ویرایش سند'), ('status_changed', 'تغییر وضعیت بازرگانی'), ('viewed', 'مشاهده'), ('customer_note', 'توضیح مشتری'), ('finance_reg', 'ثبت مالی'), ('final_approved', 'تأیید نهایی'), ('cp_approved', 'تایید طرف حساب'), ('cp_returned', 'عودت/ناقص از طرف حساب'), ('cp_rejected', 'رد/ابطال توسط طرف حساب'), ('void_initiated', 'ابطال سند توسط بازرگانی'), ('void_confirm', 'تأیید ابطال توسط مالی')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('commercial_review', 'بررسی بازرگانی'), ('temp_commercial', 'ثبت موقت بازرگانی'), ('approved', 'ثبت بازرگانی'), ('final_approved', 'تایید نهایی'), ('rejected', 'رد شده'), ('incomplete', 'ناقص'), ('returned_commercial', 'عودت به بازرگانی'), ('returned_finance', 'عودت به مالی'), ('follow_up', 'پیگیری'), ('void_pending', 'در انتظار تأیید ابطال'), ('void_confirmed', 'ابطال تأیید شده')], default='pending', max_length=20),
        ),
    ]
