# Generated by Django 6.0.2 on 2026-09-18 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0101_paymentrecord_rejection_confirmed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='return_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید عودت توسط مالی'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='return_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='تایید\u200cکننده عودت (مالی)'),
        ),
        migrations.AlterField(
            model_name='paymentactivitylog',
            name='action',
            field=models.CharField(choices=[('created', 'ثبت سند'), ('edited', 'ویرایش سند'), ('status_changed', 'تغییر وضعیت بازرگانی'), ('viewed', 'مشاهده'), ('customer_note', 'توضیح مشتری'), ('finance_reg', 'ثبت مالی'), ('final_approved', 'تأیید نهایی'), ('cp_approved', 'تایید طرف حساب'), ('cp_returned', 'عودت/ناقص از طرف حساب'), ('cp_rejected', 'رد/ابطال توسط طرف حساب'), ('void_initiated', 'عودت به مالی برای ابطال'), ('finance_void_rev', 'برگشت ثبت مالی'), ('void_confirm', 'تأیید ابطال توسط مالی'), ('admin_review_req', 'ارسال به صف بررسی مدیر'), ('admin_edited', 'ویرایش توسط مدیر سیستم'), ('finance_rej_rev', 'برگشت ثبت مالی (رد سند)'), ('rejection_confirm', 'تایید رد توسط مالی'), ('return_confirm', 'تایید عودت به مالی')], max_length=20),
        ),
    ]
