# Generated by Django 6.0.2 on 2026-09-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0102_paymentrecord_return_confirmed_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentreceipt',
            name='uniq_payment_receipt_hash',
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نسخه فعلی'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='replaced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان جایگزینی'),
        ),
        migrations.AddConstraint(
            model_name='paymentreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('payment', 'file_hash'), name='uniq_payment_receipt_hash_current'),
        ),
    ]
