# Generated by Django 6.0.2 on 2026-09-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0103_remove_paymentreceipt_uniq_payment_receipt_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='category',
            field=models.CharField(choices=[('payment', 'فیش واریزی'), ('invoice', 'فاکتور و اسناد فروش'), ('order', 'سفارش'), ('warranty', 'گارانتی'), ('agency', 'نمایندگی'), ('reconciliation', 'مغایرت\u200cگیری'), ('system', 'سیستم')], default='system', max_length=20, verbose_name='نوع'),
        ),
    ]
