# Generated by Django 6.0.2 on 2026-09-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0104_alter_usernotification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='category',
            field=models.CharField(choices=[('payment', 'فیش واریزی (قدیمی)'), ('payment_submit', 'ثبت و ویرایش فیش'), ('payment_review', 'بررسی فیش'), ('payment_finance', 'گردش مالی فیش'), ('invoice', 'فاکتور و اسناد فروش'), ('order', 'سفارش'), ('warranty', 'گارانتی'), ('agency', 'نمایندگی'), ('reconciliation', 'مغایرت\u200cگیری'), ('system', 'سیستم')], default='system', max_length=20, verbose_name='نوع'),
        ),
    ]
