# Generated by Django 6.0.2 on 2026-09-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0105_alter_usernotification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemactivitylog',
            name='action',
            field=models.CharField(choices=[('user_created', 'ایجاد کاربر'), ('user_updated', 'ویرایش کاربر'), ('password_reset', 'ریست رمز عبور'), ('profile_updated', 'ویرایش مشخصات کاربر'), ('backup_created', 'تهیه نسخه پشتیبان'), ('backup_failed', 'خطا در تهیه نسخه پشتیبان'), ('restore_started', 'شروع بازگردانی نسخه پشتیبان'), ('restore_succeeded', 'بازگردانی موفق نسخه پشتیبان'), ('restore_failed', 'خطا در بازگردانی نسخه پشتیبان')], max_length=40, verbose_name='عملیات'),
        ),
    ]
