# Generated by Django 6.0.2 on 2026-09-18 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0106_alter_systemactivitylog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=16, unique=True, verbose_name='کد دسترسی')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان تولید')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضا')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان استفاده')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='تولیدشده توسط')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='استفاده\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'کد دسترسی پشتیبان\u200cگیری',
                'verbose_name_plural': 'کدهای دسترسی پشتیبان\u200cگیری',
                'ordering': ['-generated_at', '-id'],
            },
        ),
    ]
