# Generated by Django 6.0.2 on 2026-09-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0107_backupaccesscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='customer_warranty_menu_enabled',
            field=models.BooleanField(default=False, help_text='در صورت فعال بودن، گزینه\u200cهای درخواست گارانتی، درخواست\u200cهای من و پیگیری وضعیت در منوی مشتریان نمایش داده می\u200cشود.', verbose_name='نمایش منوی «خدمات پس از فروش» برای مشتریان'),
        ),
    ]
