# Generated by Django 6.0.2 on 2026-09-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0108_alter_systemsettings_customer_warranty_menu_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypaymentnotice',
            name='customer_dismissed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انصراف مشتری از نمایش'),
        ),
    ]
