# Generated by Django 6.0.2 on 2026-09-19 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0109_dailypaymentnotice_customer_dismissed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerImpersonationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='کلید نشست')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('end_reason', models.CharField(blank=True, choices=[('manual', 'خروج دستی کارمند از حالت مشتری'), ('logout', 'خروج کامل از سامانه'), ('inactivity', 'انقضای بی\u200cفعالیت'), ('forced', 'پایان اجباری (مثلاً ورود مجدد از دستگاه دیگر)')], max_length=20, verbose_name='دلیل پایان')),
                ('customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonation_sessions_received', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonation_sessions_started', to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'جلسه ورود کارمند به\u200cعنوان مشتری',
                'verbose_name_plural': 'جلسات ورود کارمند به\u200cعنوان مشتری',
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
