# Generated by Django 6.0.2 on 2026-09-19 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0110_customerimpersonationsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='call_available',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، مشتریان می\u200cتوانند برای تماس تصویری با این کارمند (در واحد مربوطه) درخواست بدهند.', verbose_name='در دسترس برای تماس'),
        ),
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('sales', 'فروش'), ('commercial', 'بازرگانی'), ('finance', 'مالی')], max_length=16, verbose_name='واحد')),
                ('room_name', models.CharField(max_length=64, unique=True, verbose_name='نام اتاق')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پاسخ'), ('accepted', 'پذیرفته\u200cشده'), ('expired', 'بی\u200cپاسخ (منقضی\u200cشده)'), ('cancelled', 'لغوشده توسط مشتری'), ('ended', 'پایان\u200cیافته')], default='pending', max_length=12, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان درخواست')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پاسخ')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_calls', to=settings.AUTH_USER_MODEL, verbose_name='کارمند پاسخ\u200cدهنده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'درخواست تماس',
                'verbose_name_plural': 'درخواست\u200cهای تماس',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
